### PR TITLE
Add exercise sublist

### PR DESCRIPTION
**Pull request by matthewmorgan**
@exercism/ecmascripts ?

@rchavarria @joelwallis I *did* solve this one.  This solution was built entirely using TDD, with a refactor at the end to use an object instead of `if` statements.  😜

### CODE REVIEW

**Comment by rchavarria** [comment]
Congrats!! It looks really nice and clean. From my side, it's ready to be merged, but I'd prefer mergin #321 (and probably #323) and that would create some conflicts in this MR.

What do you think, @matthewmorgan ?

**Comment by rchavarria** [comment]
As #323 adds a `README` for each exercise, I think this PR should include one for the `sublist` exercise. Would you mind to include it, please?

**Comment by matthewmorgan** [comment]
@rchavarria I wouldn't mind merging the other PRs first, and adding the README is no problem.  I am a little concerned about merging #321 without modifying it to classify exercises as Katrina mentioned in the PR.  Can we merge that and do the classifying etc later?  Otherwise that's a lot of work all at once.

**Comment by rchavarria** [comment]
I hope so, I hope we can merge #321 and then work on `config.json` later. I don't know about a deadline.

In fact, I already merge a similar PR for the JavaScript track. I plan to work on the JavaScript track adding topics and selecting some *core* exercises. But I can't say how long it will take. I think I will give this task more priority than fixing ESLint errors for this track. Then, when the JavaScript track is more or less complete, we can *transfer* most of the work to this one.

**Comment by matthewmorgan** [comment]
OK @rchavarria I merged those other two PRs, added the README (some sections weren't relevant, OK to omit them?) and rebased.

Please let me know if you think there are any other changes needed.  Thanks!

**Comment by rchavarria** [comment]
Simply... awesome!, great work!

**Pull request merged**
