### PR TITLE
Make babel target current version of nodejs

### PR DESCRIPTION
**Pull request by tejasbubane**
As [suggested by Mathew](https://github.com/exercism/javascript/issues/462#issuecomment-347548041).

Once this is merged, we can close https://github.com/exercism/javascript/issues/462.

### CODE REVIEW

**Comment by tejasbubane** [comment]
Not sure why the [build](https://travis-ci.org/exercism/ecmascript/builds/335998362?utm_source=github_status&utm_medium=notification) is failing.

**Comment by matthewmorgan** [comment]
@tejasbubane I see this in the Travis logs:
> ./exercises/accumulate/package.json does not match main package.json.  Please run 'make test' locally and commit the results.

Have you tried that?

**Comment by tejasbubane** [comment]
Yes. And that is how I generated the other (exercises) package.json files. And those files have the same md5 hash:

```
➜ xecmascript bin/md5-hash package.json
455a61ca9d75a27c1dcdaf15f531f53c
➜ xecmascript bin/md5-hash exercises/accumulate/package.json
455a61ca9d75a27c1dcdaf15f531f53c
```

Which is why I am unable to figure out the problem.

**Comment by matthewmorgan** [comment]
@tejasbubane I've opened another PR with a fix.  Unfortunately I'm at a loss to explain _why_ the change is needed.  #390

**Comment by tejasbubane** [comment]
@matthewmorgan Yes, I saw those errors on local machine and also fixed couple of them but wanted to commit them separately. Before that I pushed these changes and the build failed. The travis error in both our PRs is still the same.

**Comment by matthewmorgan** [comment]
Ah, you're right!  Sorry, I didn't even notice that my build failed too... :(

Very weird.  I'll try to take another look later.

**Comment by matthewmorgan** [comment]
@tejasbubane please see my changes in #390 and comments in #396.  This appears to be formatting-related, and we have a fix.  If you want to update your PR, I'll merge it, otherwise I can merge mine as is.

**Comment by tejasbubane** [comment]
Your PR is more updated - please go ahead and merge that one.

**Pull request closed without merging**
