### PR TITLE
$ is default command line prompt

### PR DESCRIPTION
**Pull request by rootulp**

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@rootulp `%` is the default for csh and zsh, `$` is the default for bash, and `>` is the default for Windows.

I'm not opposed to his change, but by the same token I don't know what would be gained by it.

**Comment by rootulp** [comment]
@matthewmorgan thanks for the info regarding various shells! My reason for making the change is because I tend to see `$` more frequently in docs and therefore assume that it could more recognizable for new contributors.

**Comment by matthewmorgan** [comment]
You know, I think it might be best to omit the command line prompt altogether.  I see that is what the [Ruby track](https://github.com/exercism/ruby/blob/master/README.md) does.

I see how it could be confusing, but by changing it, I think we are the same risk on confusing a different set of users.  

Would you mind just getting it out entirely?

**Comment by rootulp** [comment]
I checked the [python](https://github.com/exercism/python) track and I'm on board with removing the prompt all together

**Comment by matthewmorgan** [comment]
Thanks @rootulp !

**Comment by rchavarria** [comment]
I'm late on this, but on the JavaScript track we discussed to get rid of `$` documenting the different commands (https://github.com/exercism/javascript/pull/191)

**Comment by rootulp** [comment]
Sorry @rchavarria I should've updated the PR title sooner but in commit 26658f9 I got rid of the `$`

**Pull request merged**
