### PR TITLE
update formatting in docs/ABOUT.md for Nextercism (fixes #339)

### LINKED ISSUE #85: Add new exercise: Allergies
Take the Allergies exercise from xjavascript.

### LINKED ISSUE #339: Update formatting in ABOUT.md for Nextercism
Issue https://github.com/exercism/meta/issues/85 needs some checks in this track

### PR DESCRIPTION
**Pull request by trvrfrd**
Sorry it took me so long to get around to this!

This is a first pass at fixing issue #339.

All I did was move each sentence to its own line and remove unsupported markdown (the long quotation looks kind of weird without the blockquote markup, but oh well).

The content itself could probably use some updates as well (ES2015 is no longer the most recent revision, for example), but I didn't want to overstep the bounds of the issue without checking with the maintainers.

Thanks and let me know if you have any feedback or would like me to make additional changes!

### CODE REVIEW

**Comment by rchavarria** [comment]
Yep, ES2015 is not the latest version anymore. I'm ok about updating that concept in the doc.

I don't know what other @exercism/ecmascripts think, but additionally to that, we could include something about the fact that ECMAScript plans to release a new version of the language specs every year.

**Comment by matthewmorgan** [comment]
@trvrfrd I think the last step would be to update the language to explain that 

1. this track supports 'latest' EcmaScript features via Babel, or to quote the docs:

> ... babel-preset-latest (or babel-preset-es2015, babel-preset-es2016, and babel-preset-es2017 together).

[more here](https://babeljs.io/docs/plugins/preset-env/)

2. The Ecma committee plans to update the language spec every year, and our intent is to enable those new features.

**Comment by matthewmorgan** [comment]
Woohoo!  Nice work.

**Comment by rchavarria** [comment]
Thanks @trvrfrd and @matthewmorgan for moving forward. I didn't remember about this. Sorry to let it be paused for so long.

**Comment by trvrfrd** [comment]
@rchavarria no problem! I kind of forgot about it myself 👀 thanks to you both for your help!

**Pull request merged**
